# Generated by Django 3.2.8 on 2022-06-02 19:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0025_alter_tarjetaregalo_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('visto', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
