# Generated by Django 3.2.8 on 2022-06-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0026_mensajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
