# Generated by Django 3.2.8 on 2022-06-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0027_alter_mensajes_codigo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensajes',
            new_name='Mensaje',
        ),
    ]
