# Generated by Django 3.2.8 on 2022-06-02 22:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tienda.models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0028_rename_mensajes_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracin',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('valoracion', models.IntegerField(max_length=5)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('usaurio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.videojuego')),
            ],
        ),
        migrations.CreateModel(
            name='DLC',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField(blank=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, max_length=20)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.videojuego')),
            ],
        ),
        migrations.CreateModel(
            name='Desarrolladora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[(tienda.models.tipoDesarrolladora['I'], 'indie'), (tienda.models.tipoDesarrolladora['E'], 'empresa')], max_length=2)),
                ('nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('usaurio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.videojuego')),
            ],
        ),
    ]
