# Generated by Django 3.2.8 on 2022-06-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0029_comentario_desarrolladora_dlc_valoracin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Valoracin',
            new_name='Valoracion',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='usaurio',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='valoracion',
            old_name='usaurio',
            new_name='usuario',
        ),
    ]
